### ISSUE TITLE
`SporeWithEnv` is not unpicklable when it is treated as `Spore`

### ISSUE THREAD

**Issue by jvican** [heathermiller/spores#39]
This is a severe bug.
  
Spores are very useful, specially when they can reference to variables in their context of creation, declaring them in the spore header. This example reproduces how such spores can't be unpickled.
  
```scala
  def test[T: Pickler: Unpickler](msg: T): Unit = {

    // 1. generate unpickler
    val unpickler = implicitly[Unpickler[T]]
    
    // 2. pickle value
    val p = msg.pickle

    val pp = p.unpickle[T]
    println("it worked!")

  }

  // Works as expected
  val s = spore[Unit, Int]{Unit => 1}
  test(s)

  // It works because the generated unpickler recognises that this
  // is not a plain spore but an instance of `SporeWithEnv`
  val n1 = 1
  val s2 = spore[Unit, Int]{
    val g = n1
    Unit => g
  }
  test(s2)  

  // Doesn't work because we have a spore with a header
  // and we're casting to `Spore` when it's actually `SporeWithEnv`
  // Therefore, the unpickler is badly generated somehow
  val n2 = 1
  val s3: Spore[Unit,Int] = spore[Unit,Int]{
    val g = n2
    Unit => g
  }
  test(s3)
```
  
For the record, this is the output:
```
[info] it worked!
[info] it worked!
[error] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 98
[error] 	at scala.pickling.binary.ByteArrayInput.getByte(BinaryInput.scala:129)
[error] 	at scala.pickling.binary.BinaryPickleReader$$anonfun$1.apply(BinaryPickle.scala:177)
[error] 	at scala.pickling.binary.BinaryPickleReader$$anonfun$1.apply(BinaryPickle.scala:164)
[error] 	at scala.pickling.PickleTools$class.withHints(Tools.scala:521)
[error] 	at scala.pickling.binary.BinaryPickleReader.withHints(BinaryPickle.scala:160)
[error] 	at scala.pickling.binary.BinaryPickleReader.beginEntry(BinaryPickle.scala:164)
[error] 	at wc.SelfDescribingTest$SporeUnpickler$macro$10$2$.unpickle(SelfDescribingTest.scala:41)
[error] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[error] 	at wc.SelfDescribingTest$SporeUnpickler$macro$10$2$.unpickleEntry(SelfDescribingTest.scala:41)
[error] 	at scala.pickling.functions$.unpickle(functions.scala:11)
[error] 	at scala.pickling.UnpickleOps.unpickle(Ops.scala:23)
[error] 	at wc.SelfDescribingTest$.test(SelfDescribingTest.scala:25)
[error] 	at wc.SelfDescribingTest$.delayedEndpoint$wc$SelfDescribingTest$1(SelfDescribingTest.scala:41)
[error] 	at wc.SelfDescribingTest$delayedInit$body.apply(SelfDescribingTest.scala:15)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at wc.SelfDescribingTest$.main(SelfDescribingTest.scala:15)
[error] 	at wc.SelfDescribingTest.main(SelfDescribingTest.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
```
  
As you see, we get two `it works` and then an `ArrayIndexOutOfBoundsException`.
  
This bug is very problematic because most of the times the library developers (me included) don't care to expect a subclass of `Spore` when they want to serialize something. They just expect an object of type `Spore` and this obviously typechecks since `SporeWithEnv` <: `Spore`.
  
My proposed solution is to force the macros to check if the pickled/unpickled `Spore` corresponds to a subclass of it. My hunch is that the main problem is in the `Unpickler`, not the `Pickler`.
  
BTW, I'm using last version `0.2.1`.

**Comment by jvican** [comment]
Addressed by #41.
